Configuration: add "Global profile configuration"
Behat/docs pull request #155
Opened 2024-11-04 09:35 UTC by jdeniau

Add documentation for https://github.com/Behat/Behat/pull/1501 and https://github.com/Behat/Behat/pull/1513

2024-11-05 00:24 UTC, acoulton requested changes
Couple of tiny wording suggestions, otherwise this looks good and ready to merge once the feature PRs merge.

2024-11-05 00:24 UTC, acoulton commented on user_guide/configuration.rst
> +        config: # these are the default value
```suggestion
        config: # these are the default values
```

2024-11-05 00:24 UTC, acoulton commented on user_guide/configuration.rst
> +This way, behat will stop on default environment and won't be strict, but will not stop and will be strict on CI.
```suggestion
This way, with the default profile behat will stop on failure and won't be strict, but will not stop and will be strict if the CI profile is selected.
```

2024-11-05 08:32 UTC, jdeniau commented
I convert this to "draft" until https://github.com/Behat/Behat/pull/1516#issuecomment-2456532362 is resolved.

2024-11-08 13:22 UTC, jdeniau commented
> I convert this to "draft" until [Behat/Behat#1516 (comment)](https://github.com/Behat/Behat/pull/1516#issuecomment-2456532362) is resolved.

Mark as ready now that 3.16 is out.

2024-11-08 13:29 UTC, carlos-granados requested changes
Small change needed

2024-11-08 13:29 UTC, carlos-granados commented on user_guide/configuration.rst
> +
I think you should remove this extra blank line

2024-11-08 14:04 UTC, carlos-granados approved these changes
All good, thanks @jdeniau

2024-11-08 17:29 UTC, acoulton approved these changes

2024-11-08 17:30 UTC, acoulton commented
Great, thanks @jdeniau !

2024-11-08 17:30 UTC, merged